services:
  # Your existing Reddit API service
  - type: web
    name: reddit-scraper-api
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        sync: false
  
  # New Telegram bot service
  - type: worker
    name: reddit-telegram-bot
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: REDDIT_API_URL
        value: https://reddit-scraper-api-yp5t.onrender.com
      - key: N8N_WEBHOOK_URL
        sync: false
      - key: ALLOWED_USERS
        value: "5028346767,6150863409,5157639618"
