services:
  - type: worker
    name: reddit-scraper-bot
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        value: RedditScraperBot/1.0 by YourRedditUsername
      - key: N8N_WEBHOOK_URL
        sync: false
      - key: ALLOWED_USERS
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: reddit-bot-redis
          property: connectionString

# Optional Redis instance for rate limiting
databases:
  - name: reddit-bot-redis
    type: redis
    region: oregon
    plan: free
    maxmemoryPolicy: allkeys-lru
