services:
  - type: web
    name: reddit-scraper-api
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn.conf.py
    pythonVersion: "3.11"
    envVars:
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        value: RedditScraper/1.0
      - key: OPENAI_API_KEY
        sync: false
      - key: API_KEY
        generateValue: true
