services:
  - type: web
    name: reddit-scraper-api
    runtime: python
    plan: free
    buildCommand: pip install --only-binary :all: -r requirements.txt
    startCommand: gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    pythonVersion: "3.11"
    envVars:
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        value: RedditScraper/1.0
      - key: OPENAI_API_KEY
        sync: false
      - key: API_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: reddit-scraper-db
          property: connectionString

databases:
  - name: reddit-scraper-db
    plan: free
    ipAllowList: []
